sudo: required
services:
  - docker

before_install:
  - docker build -t dominic70/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dominic70/docker-react npm run test
  # - docker run dominic70/docker-react npm run test -- --coverage <--does not exits